
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 16;
  public static final int MENOR = 21;
  public static final int ENTAO = 6;
  public static final int IGUAL = 19;
  public static final int PONTO = 14;
  public static final int ACHAVES = 27;
  public static final int LEIASENSOR = 4;
  public static final int ID = 29;
  public static final int INTEIRO = 12;
  public static final int PONTOVIRGULA = 24;
  public static final int ATRIBUICAO = 23;
  public static final int FUNCAO = 8;
  public static final int MAIS = 15;
  public static final int AVANCE = 2;
  public static final int APARENTESES = 25;
  public static final int RETORNE = 9;
  public static final int MULT = 17;
  public static final int EOF = 0;
  public static final int DIFERENTE = 20;
  public static final int DIV = 18;
  public static final int VIRE = 3;
  public static final int TEXTO = 31;
  public static final int NUMERO = 30;
  public static final int MAIOR = 22;
  public static final int error = 1;
  public static final int SE = 5;
  public static final int ENQUANTO = 7;
  public static final int FCHAVES = 28;
  public static final int FIM = 11;
  public static final int FPARENTESES = 26;
  public static final int LOGICO = 13;
  public static final int INICIO = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AVANCE",
  "VIRE",
  "LEIASENSOR",
  "SE",
  "ENTAO",
  "ENQUANTO",
  "FUNCAO",
  "RETORNE",
  "INICIO",
  "FIM",
  "INTEIRO",
  "LOGICO",
  "PONTO",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAIOR",
  "ATRIBUICAO",
  "PONTOVIRGULA",
  "APARENTESES",
  "FPARENTESES",
  "ACHAVES",
  "FCHAVES",
  "ID",
  "NUMERO",
  "TEXTO"
  };
}

